# Generated by Django 2.2.4 on 2019-10-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
