# Generated by Django 2.2.4 on 2019-10-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0006_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ragister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
            ],
        ),
    ]
