# Generated by Django 2.2.4 on 2019-10-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0007_ragister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ragister',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
