# Generated by Django 2.2.4 on 2019-10-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0009_auto_20191008_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(error_messages={'unique': 'This email is already in use'}, max_length=50, unique=True)),
            ],
        ),
    ]
