# Generated by Django 2.2.4 on 2019-10-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0010_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'unique': 'This email is already in use'}, max_length=300, unique=True),
        ),
    ]
