# Generated by Django 2.2.4 on 2019-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0011_auto_20191008_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
