# Generated by Django 2.2.4 on 2019-10-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0013_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Signup1',
        ),
    ]
