# Generated by Django 2.2.4 on 2019-10-08 12:26

import Ragistration.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ragistration', '0014_auto_20191008_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100)),
                ('Job_Role', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Offical_Websitee', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'You are allready apply'}, max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, validators=[Ragistration.validators.validate_username_length, Ragistration.validators.validate_username_alphadigits], verbose_name='User name')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=30, validators=[Ragistration.validators.validate_password_length, Ragistration.validators.validate_password_digit, Ragistration.validators.validate_password_uppercase])),
                ('password2', models.CharField(max_length=30)),
                ('Birth_date', models.DateField(verbose_name='What is your birth date?')),
                ('gender', models.CharField(max_length=6)),
                ('college', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15, validators=[Ragistration.validators.validate_phonenumber])),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
