# Generated by Django 2.2.4 on 2019-10-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0015_apply_post_signup1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
