# Generated by Django 2.2.4 on 2019-10-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0019_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='college',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
