# Generated by Django 2.2.4 on 2019-10-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0023_auto_20191010_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='college',
        ),
    ]
