# Generated by Django 2.2.4 on 2019-10-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0025_auto_20191010_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
