# Generated by Django 2.2.4 on 2019-10-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ragistration', '0026_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='Contact',
        ),
    ]
